"""initial schema

Revision ID: f3347e3a6057
Revises: 
Create Date: 2026-09-02 13:46:23.289405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3347e3a6057'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_id'), 'chat_logs', ['id'], unique=False)
    op.create_index(op.f('ix_chat_logs_session_id'), 'chat_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_user_email'), 'chat_logs', ['user_email'], unique=False)
    op.create_table('platform_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_configs_id'), 'platform_configs', ['id'], unique=False)
    op.create_index(op.f('ix_platform_configs_key'), 'platform_configs', ['key'], unique=True)
    op.create_table('sla_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('promised_value', sa.String(), nullable=True),
    sa.Column('actual_value', sa.String(), nullable=True),
    sa.Column('is_breached', sa.Boolean(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_records_id'), 'sla_records', ['id'], unique=False)
    op.create_index(op.f('ix_sla_records_tenant_id'), 'sla_records', ['tenant_id'], unique=False)
    op.create_table('underwriting_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('applicant_age', sa.Integer(), nullable=True),
    sa.Column('applicant_name', sa.String(), nullable=True),
    sa.Column('applicant_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('premium_monthly', sa.String(), nullable=True),
    sa.Column('premium_annual', sa.String(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_underwriting_decisions_id'), 'underwriting_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_underwriting_decisions_product_type'), 'underwriting_decisions', ['product_type'], unique=False)
    op.create_index(op.f('ix_underwriting_decisions_status'), 'underwriting_decisions', ['status'], unique=False)
    op.create_index(op.f('ix_underwriting_decisions_tenant_id'), 'underwriting_decisions', ['tenant_id'], unique=False)
    op.create_table('underwriting_manuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('encrypted_file_path', sa.String(), nullable=True),
    sa.Column('encryption_key_id', sa.String(), nullable=True),
    sa.Column('compiled_rules', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_underwriting_manuals_filename'), 'underwriting_manuals', ['filename'], unique=False)
    op.create_index(op.f('ix_underwriting_manuals_id'), 'underwriting_manuals', ['id'], unique=False)
    op.create_index(op.f('ix_underwriting_manuals_product_type'), 'underwriting_manuals', ['product_type'], unique=False)
    op.create_index(op.f('ix_underwriting_manuals_tenant_id'), 'underwriting_manuals', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('webhook_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_configs_id'), 'webhook_configs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_configs_tenant_id'), 'webhook_configs', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('holder_name', sa.String(), nullable=True),
    sa.Column('holder_email', sa.String(), nullable=True),
    sa.Column('holder_age', sa.Integer(), nullable=True),
    sa.Column('coverage_blocks', sa.String(), nullable=True),
    sa.Column('premium_monthly', sa.Float(), nullable=True),
    sa.Column('premium_annual', sa.Float(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('manual_id', sa.Integer(), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['underwriting_manuals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('insurer_share', sa.Float(), nullable=True),
    sa.Column('partner_commission', sa.Float(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('gateway_reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_webhook_configs_tenant_id'), table_name='webhook_configs')
    op.drop_index(op.f('ix_webhook_configs_id'), table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_underwriting_manuals_tenant_id'), table_name='underwriting_manuals')
    op.drop_index(op.f('ix_underwriting_manuals_product_type'), table_name='underwriting_manuals')
    op.drop_index(op.f('ix_underwriting_manuals_id'), table_name='underwriting_manuals')
    op.drop_index(op.f('ix_underwriting_manuals_filename'), table_name='underwriting_manuals')
    op.drop_table('underwriting_manuals')
    op.drop_index(op.f('ix_underwriting_decisions_tenant_id'), table_name='underwriting_decisions')
    op.drop_index(op.f('ix_underwriting_decisions_status'), table_name='underwriting_decisions')
    op.drop_index(op.f('ix_underwriting_decisions_product_type'), table_name='underwriting_decisions')
    op.drop_index(op.f('ix_underwriting_decisions_id'), table_name='underwriting_decisions')
    op.drop_table('underwriting_decisions')
    op.drop_index(op.f('ix_sla_records_tenant_id'), table_name='sla_records')
    op.drop_index(op.f('ix_sla_records_id'), table_name='sla_records')
    op.drop_table('sla_records')
    op.drop_index(op.f('ix_platform_configs_key'), table_name='platform_configs')
    op.drop_index(op.f('ix_platform_configs_id'), table_name='platform_configs')
    op.drop_table('platform_configs')
    op.drop_index(op.f('ix_chat_logs_user_email'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_session_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    # ### end Alembic commands ###
