import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { Settings } from 'lucide-react';

import { API_URL } from '../../services/api';

export function PolicyConfig() {
  const { token } = useAuth();
  const [prefixes, setPrefixes] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (token) loadConfig();
  }, [token]);

  const loadConfig = async () => {
    try {
        const res = await fetch(`${API_URL}/config/policy/prefixes`, {
            headers: { Authorization: `Bearer ${token}` }
        });
        if (res.ok) {
            setPrefixes(await res.json());
        }
    } catch (e) {
        console.error(e);
    }
  };

  const handleUpdate = async (product: string, newPrefix: string) => {
    try {
        setLoading(true);
        const res = await fetch(`${API_URL}/config/policy/prefixes`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ product_type: product, prefix: newPrefix })
        });
        if (res.ok) {
            // Update local state
            setPrefixes((prev: Record<string, string>) => ({ ...prev, [product]: newPrefix }));
            alert(`Prefix for ${product} updated to ${newPrefix}`);
        }
    } finally {
        setLoading(false);
    }
  };

  return (
    <div className="card max-w-2xl">
        <div className="p-6 border-b border-slate-200">
            <h3 className="text-lg font-bold text-slate-900 flex items-center">
                <Settings className="w-5 h-5 mr-2" /> Policy Number Configuration
            </h3>
            <p className="text-slate-500 text-sm mt-1">
                Define the unique prefixes for policy numbers generated by the system.
            </p>
        </div>

        <div className="p-6 space-y-4">
            {Object.entries(prefixes).map(([product, prefix]) => (
                <div key={product} className="flex items-center justify-between p-4 bg-slate-50 rounded-lg border border-slate-200">
                    <div>
                        <p className="font-medium text-slate-900 capitalize">{product.replace('_', ' ')}</p>
                        <p className="text-xs text-slate-500">Current Next: {String(prefix)}-...-0000X</p>
                    </div>
                    <div className="flex items-center gap-2">
                        <input
                            type="text"
                            aria-label={`Policy prefix for ${product.replace('_', ' ')}`}
                            title={`Policy prefix for ${product.replace('_', ' ')}`}
                            defaultValue={String(prefix)}
                            disabled={loading}
                            className="w-24 px-3 py-2 border rounded font-mono text-center uppercase disabled:opacity-50"
                            maxLength={5}
                            onBlur={(e: React.FocusEvent<HTMLInputElement>) => {
                                if (e.target.value !== String(prefix)) {
                                    handleUpdate(product, e.target.value);
                                }
                            }}
                        />
                        <span className="text-xs text-slate-400">Auto-save on blur</span>
                    </div>
                </div>
            ))}
            
            {Object.keys(prefixes).length === 0 && (
                <p className="text-center text-slate-500">Loading configurations...</p>
            )}
        </div>
    </div>
  );
}
