from sqlalchemy import Column, Integer, String, Text, Float, DateTime
from sqlalchemy.sql import func
from app.db.base import Base

class ChatLog(Base):
    __tablename__ = "chat_logs"

    id = Column(Integer, primary_key=True, index=True)
    # Session grouping — UUID generated by the client on first message and
    # echoed back; subsequent turns in the same conversation share the id.
    session_id = Column(String, nullable=True, index=True)
    user_email = Column(String, nullable=True, index=True)
    role = Column(String)  # consumer/agent/partner
    message = Column(Text)
    response = Column(Text)
    action = Column(String)
    latency_ms = Column(Float)
    model = Column(String)
    status = Column(String) # success/error
    timestamp = Column(DateTime(timezone=True), server_default=func.now())
